application: 50apps-week3
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  
- url: /.*
  script: week3.app

libraries:
- name: jinja2
  version: latest    
